FROM node:22-slim AS base

WORKDIR /app

RUN npm install -g pnpm@10.8.0

COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml ./

COPY apps/frontend/package.json ./apps/frontend/
COPY packages/zero-shared/package.json ./packages/zero-shared/

RUN pnpm install --filter frontend... --frozen-lockfile

FROM base AS development

WORKDIR /app

COPY packages/zero-shared ./packages/zero-shared
COPY apps/frontend ./apps/frontend

WORKDIR /app/apps/frontend

EXPOSE 5173

CMD ["pnpm", "dev"]
